# Generated by Django 6.0.6 on 2026-07-09 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('GASTO', 'Gasto (-)')], max_length=10)),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('RESERVA', 'Consumo Reservas'), ('INSUMOS', 'Insumos / Alimentos'), ('SERVICIOS', 'Servicios Públicos'), ('NOMINA', 'Nómina / Personal'), ('OTROS', 'Otros Gastos')], default='OTROS', max_length=20)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
