# Generated by Django 6.0.6 on 2026-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('GASTO', 'Gasto (-)')], default='GASTO', max_length=10),
        ),
    ]
