# Generated by Django 6.0.6 on 2026-07-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('TRANSFERENCIA', 'Transferencia (Nequi/Bancolombia)'), ('TARJETA', 'Tarjeta Débito/Crédito')], default='EFECTIVO', max_length=20),
            preserve_default=False,
        ),
    ]
