# Generated by Django 6.0.6 on 2026-07-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_plato_reserva_estado_platoreserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platoreserva',
            name='plato',
        ),
        migrations.RemoveField(
            model_name='platoreserva',
            name='reserva',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
        migrations.DeleteModel(
            name='PlatoReserva',
        ),
    ]
